#
# Dockerfile for building MySQL images
# 
# https://github.com/sakurallj/docker-lnmp.git
#

FROM hub.c.163.com/library/mysql:8.0.1
MAINTAINER sakurallj <liaolingjia@163.com>

ENV TZ "Asia/Shanghai"

 